"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url

from utils.huey_config import HUEY

HUEY = HUEY

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


LOCAL_APPS = [
    "apps.helpers",
    "apps.Account",
    "corsheaders",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework.authtoken",
    'huey.contrib.djhuey',
]


INSTALLED_APPS += LOCAL_APPS + THIRD_PARTY_APPS


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [ os.path.join(BASE_DIR, 'templates'),],
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }




DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.oracle',
#         'NAME': (
#             "(DESCRIPTION="
#             "(ADDRESS=(PROTOCOL=TCP)"
            
#             f"(HOST={config("DB_HOST")})"  
#             f"(PORT={config("DB_PORT")}))"
#             "(CONNECT_DATA="
#             f"(SERVICE_NAME={config("DB_SERVICE")})))"
#         ),
#         'USER': config("DB_USER"),
#         'PASSWORD': config("DB_PASSWORD"), 
#         # 'CONN_MAX_AGE': 60, 
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOW_ALL_ORIGINS = False 
CORS_ALLOW_CREDENTIALS = True 
CORS_ALLOWED_ORIGINS = [ 
    'http://localhost:5173',
    "http://10.240.129.173:9033"
] 


CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "Authorization"
]




LOG_DIR = os.path.join(BASE_DIR, "IP_logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'netsight_debug.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 4,
            'formatter': 'verbose',
           
        },
        'info_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'night_info.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 4,
            'formatter': 'verbose',
           
        },
    },
    'formatters': {
        'verbose': {
            'format': '"%(process)s- %(thread)s-%(asctime)s - %(levelname)s - %(message)s'
        },
    },
    'loggers': {
        '': {
            'handlers': ['debug_file', 'info_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


NETMIKO_DEVICE_MAP = {
    "juniper_junos": "juniper_junos",
    "juniper_bras": "juniper_junos",
    "cisco_xr": "cisco_xr",
    "cisco_xe": "cisco_xe",
    "huawei": "huawei",
    "nokia_sros": "nokia_sros",
    "ciena_saos": "ciena_saos",
    "generic": "generic",
}
 

DEVICE_CREDENTIALS = {

    "juniper_junos": {
        "username": config("JUNIPER_USER", default=""),
        "password": config("JUNIPER_PASS", default=""),
    },
    "juniper_bras": {
        "username": config("JUNIPER_BRAS_USER", default=""),
        "password": config("JUNIPER_BRAS_PASS", default=""),
    },
    "cisco_xr": {
        "username": config("CISCO_XR_USER", default=""),
        "password": config("CISCO_XR_PASS", default=""),
    },
    "cisco_xe": {
        "username": config("CISCO_XE_USER", default=""),
        "password": config("CISCO_XE_PASS", default=""),
    },
    "huawei": {
        "username": config("HUAWEI_USER", default=""),
        "password": config("HUAWEI_PASS", default=""),
    },
    "nokia_sros": {
        "username": config("NOKIA_SROS_USER", default=""),
        "password": config("NOKIA_SROS_PASS", default=""),
    },
     "ciena_saos": {
        "username": config("CIENA_SAOS_USER", default=""),
        "password": config("CIENA_SAOS_PASS", default=""),
    },
    "generic": {
        "username": config("GENERIC_USER", default=""),
        "password": config("GENERIC_PASS", default=""),
    },
}



DEVICE_CONFIG_CREDENTIALS = {

    "juniper_junos": {
        "username": config("JUNIPER_CONFIG_USER", default=""),
        "password": config("JUNIPER_CONFIG_PASS", default=""),
    },
    "juniper_bras": {
        "username": config("JUNIPER_CONFIG_BRAS_USER", default=""),
        "password": config("JUNIPER_CONFIG_BRAS_PASS", default=""),
    },

    "cisco_xr": {
        "username": config("CISCO_CONFIG_XR_USER", default=""),
        "password": config("CISCO_CONFIG_XR_PASS", default=""),
    },
    "cisco_xe": {
        "username": config("CISCO_CONFIG_XE_USER", default=""),
        "password": config("CISCO_CONFIG_XE_PASS", default=""),
    },
    "huawei": {
        "username": config("HUAWEI_CONFIG_USER", default=""),
        "password": config("HUAWEI_CONFIG_PASS", default=""),
    },
    "nokia_sros": {
        "username": config("NOKIA_CONFIG_SROS_USER", default=""),
        "password": config("NOKIA_CONFIG_SROS_PASS", default=""),
    },
     "ciena_saos": {
        "username": config("CIENA_CONFIG_SAOS_USER", default=""),
        "password": config("CIENA_CONFIG_SAOS_PASS", default=""),
    },
}

# Convert to int safely
GLOBAL_SSH_LIMIT = int(config('GLOBAL_SSH_LIMIT', default=50))
THREADS = int(config('THREADS', default=10))
BATCH_SIZE = int(config('BATCH_SIZE', default=100))

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        # optionally add SessionAuthentication if needed
    ),
}


MAX_COMMANDS = int(config("MAX_COMMANDS"))
MULTI_DEVICE= int(config("MULTI_DEVICE"))