# Generated by Django 5.2.8 on 2025-11-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_ips', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('device_type', models.CharField(choices=[('juniper_junos', 'Juniper JunOS'), ('cisco_ios', 'Cisco IOS'), ('huawei_vrp', 'Huawei VRP'), ('mikrotik', 'MikroTik RouterOS'), ('arista_eos', 'Arista EOS'), ('nokia', 'Nokia')], default='juniper_junos', max_length=50)),
                ('commands', models.TextField()),
                ('status', models.CharField(default='RUNNING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ip', models.CharField(max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('command_output', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='helpers.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
