# Generated by Django 5.2.8 on 2025-12-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_alter_job_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='success',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='IPBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ips', models.JSONField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Batch_tasks', to='helpers.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
