# Generated by Django 5.2.8 on 2026-01-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_alter_job_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='device_type',
            field=models.CharField(choices=[('juniper_junos', 'Juniper JunOS'), ('juniper_junos', 'Juniper BRAS'), ('cisco_xr', 'Cisco XR IOS'), ('cisco_xe', 'Cisco XE IOS'), ('huawei', 'Huawei VRP'), ('nokia_sros', 'Nokia'), ('ciena_saos', 'Ciena Saos')], default='juniper_junos', max_length=50),
        ),
    ]
