# Generated by Django 5.2.8 on 2026-01-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0006_alter_job_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/jobs/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='device_type',
            field=models.CharField(blank=True, choices=[('juniper_junos', 'Juniper JunOS'), ('juniper_junos', 'Juniper BRAS'), ('cisco_xr', 'Cisco XR'), ('cisco_xe', 'Cisco XE'), ('huawei', 'Huawei'), ('nokia_sros', 'Nokia'), ('ciena_saos', 'Ciena')], default='juniper_junos', max_length=50, null=True),
        ),
    ]
