# Generated by Django 5.2.8 on 2026-03-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0007_job_file_alter_job_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='execution_mode',
            field=models.CharField(choices=[('readonly', 'Read Only'), ('config', 'Configuration')], default='readonly', max_length=20),
        ),
    ]
