# Generated by Django 5.2.8 on 2026-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0009_configexecutionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='device_type',
            field=models.CharField(blank=True, choices=[('juniper_junos', 'Juniper JunOS'), ('juniper_bras', 'Juniper BRAS'), ('cisco_xr', 'Cisco XR'), ('cisco_xe', 'Cisco XE'), ('huawei', 'Huawei'), ('nokia_sros', 'Nokia'), ('ciena_saos', 'Ciena')], default='juniper_junos', max_length=50, null=True),
        ),
    ]
