# Generated by Django 5.2.8 on 2026-04-08 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0010_alter_job_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipresult',
            name='job',
        ),
        migrations.RemoveField(
            model_name='iptask',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='commands',
        ),
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('host_ip', models.GenericIPAddressField()),
                ('command', models.TextField()),
                ('output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField()),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_tasks', to='helpers.job')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.DeleteModel(
            name='IPBatch',
        ),
        migrations.DeleteModel(
            name='IPResult',
        ),
        migrations.DeleteModel(
            name='IPTask',
        ),
        migrations.AddIndex(
            model_name='commandexecution',
            index=models.Index(fields=['job', 'status'], name='helpers_com_job_id_37f3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='commandexecution',
            index=models.Index(fields=['host_ip'], name='helpers_com_host_ip_4f89b0_idx'),
        ),
    ]
