# Generated by Django 5.2.8 on 2026-04-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0011_remove_ipresult_job_remove_iptask_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
