# Generated by Django 5.2.8 on 2026-04-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0012_job_total_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCTCiscoT4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ip_address', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('total_vrfs', models.IntegerField(default=0)),
                ('deviated_vrfs', models.IntegerField(default=0)),
                ('total_l2vpn', models.IntegerField(default=0)),
                ('deviated_l2vpn', models.IntegerField(default=0)),
                ('total_bgp', models.IntegerField(default=0)),
                ('deviated_bgp', models.IntegerField(default=0)),
                ('total_interfaces', models.IntegerField(default=0)),
                ('deviated_interfaces', models.IntegerField(default=0)),
                ('total_evi', models.IntegerField(default=0)),
                ('deviated_evi', models.IntegerField(default=0)),
                ('status', models.CharField(default='Not Started', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GCTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('vendor', models.CharField(max_length=255)),
                ('nw_type', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('inventory_count', models.IntegerField(default=0)),
                ('gct_availability', models.BooleanField(default=False)),
                ('gct_sharedon', models.DateTimeField(blank=True, null=True)),
                ('development_status', models.CharField(default='Not Started', max_length=255)),
                ('deviation_count', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('query_inv', models.TextField(blank=True, null=True)),
                ('exec_endpoint', models.CharField(blank=True, max_length=1000, null=True)),
                ('get_endpoint', models.CharField(blank=True, max_length=1000, null=True)),
                ('current_status', models.CharField(default='Not Started', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='device_type',
            field=models.CharField(blank=True, choices=[('juniper_junos', 'Juniper JunOS'), ('juniper_bras', 'Juniper BRAS'), ('cisco_xr', 'Cisco XR'), ('cisco_xe', 'Cisco XE'), ('huawei', 'Huawei'), ('nokia_sros', 'Nokia'), ('ciena_saos', 'Ciena'), ('generic', 'Generic')], default='juniper_junos', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CiscoT4Exec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('command', models.TextField(blank=True, null=True)),
                ('command_output', models.TextField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cisco_t4_execs', to='helpers.gctciscot4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GCTCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('command', models.TextField()),
                ('gct_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='helpers.gctmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gctciscot4',
            name='gct_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='helpers.gctmodel'),
        ),
    ]
