# Generated by Django 5.2.8 on 2026-04-30 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0013_gctciscot4_gctmodel_alter_job_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('host_ip', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='helpers.job')),
            ],
            options={
                'unique_together': {('job', 'host_ip')},
            },
        ),
        migrations.CreateModel(
            name='DeviceMultiCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('command', models.TextField()),
                ('sequence', models.IntegerField()),
                ('output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='helpers.deviceexecution')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='GCTDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deviation_type', models.CharField(max_length=255)),
                ('deviation', models.BooleanField(blank=True, null=True)),
                ('gct_data', models.JSONField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cisco_t4_deviations', to='helpers.gctciscot4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
