# Generated by Django 5.2.8 on 2026-05-06 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0014_deviceexecution_devicemulticommand_gctdeviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gctciscot4',
            name='circle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CiscoT4Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('command_output', models.TextField()),
                ('complete_data', models.TextField()),
                ('inv_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gct_inv_id', to='helpers.gctciscot4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CiscoT4Exec',
        ),
    ]
