# Generated by Django 5.2.14 on 2026-05-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0015_remove_gctdeviation_inventory_gctciscot4_circle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GCTDeviation',
        ),
    ]
