# Generated by Django 5.2.8 on 2025-11-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MISSignupRequest',
            new_name='DCTSignupRequest',
        ),
    ]
